Vmeet/Vmeet/Controllers/ToplantilarController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Vmeet.Models;
using Vmeet.Utility;

namespace Vmeet.Controllers
{
    public class ToplantilarController : Controller
    {
        private VmeetDbContext db = new VmeetDbContext();
        private DosyaYoneticisi dy;
        private ApplicationUserManager userManager;

        public ToplantilarController()
        {
            dy = new DosyaYoneticisi(db);
            userManager = new ApplicationUserManager(new UserStore<ApplicationUser>(db));
        }

        public ActionResult Stream()
        {
            return View();
        }
        // GET: Toplantilar
        public ActionResult Index()
        {
            if (User.Identity.IsAuthenticated)
            {
                var currentUser = User.Identity.GetUserId();
                var ozelToplantilar = db.Katilimcilar.Include(x => x.Toplanti).Where(x => x.ApplicationUserID == currentUser).Select(x=>x.Toplanti);
                var yonettigiToplantilar = db.Toplantilar.Where(x => x.YoneticiID == currentUser);
                var Toplantilar = db.Toplantilar.Where(x => !x.OzelMi).Union(ozelToplantilar);
                Toplantilar = Toplantilar.Union(yonettigiToplantilar);
                Toplantilar = Toplantilar.OrderByDescending(x => x.BaslamaZamani);
                return View("UyeIndex", Toplantilar.ToList());
            }
            else
            {
                var model = new ToplantilarViewModel
                {
                    Toplantilar = db.Toplantilar.Where(x => x.OzelMi.Equals(false)).ToList(),
                    Avatarlar = db.Avatarlar.ToList()
                    
                };
                return View(model);             
            }
           
        }
        [Authorize]
        public ActionResult UyeIndex()
        {
            return View(db.Toplantilar.ToList());
        }

        // GET: Toplantilar/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Toplanti toplanti = db.Toplantilar.Find(id);
            if (toplanti == null)
            {
                return HttpNotFound();
            }
            return View(toplanti);
        }


        // GET: Toplantilar/Create
        [Authorize]  //yetkilendirme
        public ActionResult Create()
        {
            
            return View();
        }

        // POST: Toplantilar/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,YoneticiID,ToplantiAdi,Konu,BaslamaZamani,BitisZamani,OzelMi")] Toplanti toplanti)
        {
            toplanti.YoneticiID = User.Identity.GetUserId();

            if (ModelState.IsValid)
                {
                    db.Toplantilar.Add(toplanti);
                    db.SaveChanges();
                    return RedirectToAction("Yonet", new { id=toplanti.ID });
                }
   
            return View(toplanti);
        }
        

        // GET: Toplantilar/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            //burada
            Toplanti toplanti = db.Toplantilar.Find(id);
            toplanti.YoneticiID = User.Identity.GetUserId();

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            
            if (toplanti == null)
            {
                return HttpNotFound();
            }
            return View(toplanti);
        }
        [Authorize]
        // POST: Toplantilar/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,ToplantiAdi,Konu,BaslamaZamani,BitisZamani,OzelMi")] Toplanti toplanti)
        {
            if (db.Toplantilar.Find(toplanti.ID) == null || User.Identity.GetUserId() != db.Toplantilar.Find(toplanti.ID).YoneticiID)
            {
                return RedirectToAction("Index");
            }
                        
            if (ModelState.IsValid)
            {
                db.Toplantilar.Find(toplanti.ID).BaslamaZamani = toplanti.BaslamaZamani;
                db.Toplantilar.Find(toplanti.ID).BitisZamani = toplanti.BitisZamani;
                db.Toplantilar.Find(toplanti.ID).Konu = toplanti.Konu;
                db.Toplantilar.Find(toplanti.ID).ToplantiAdi = toplanti.ToplantiAdi;
                db.Toplantilar.Find(toplanti.ID).OzelMi = toplanti.OzelMi;
                db.Toplantilar.Find(toplanti.ID).Cikti = toplanti.Cikti;
                db.SaveChanges();
                return RedirectToAction("Yonet", new { id = toplanti.ID });
            }
            return View(toplanti);
        }

        // GET: Toplantilar/Delete/5
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Toplanti toplanti = db.Toplantilar.Find(id);
            if (toplanti == null || User.Identity.GetUserId() != toplanti.YoneticiID)
            {
                return RedirectToAction("Index");
            }
            if (toplanti == null)
            {
                return HttpNotFound();
            }
            return View(toplanti);
        }

        // POST: Toplantilar/Delete/5
        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Toplanti toplanti = db.Toplantilar.Find(id);
            if (toplanti == null || User.Identity.GetUserId() != toplanti.YoneticiID)
            {
                return RedirectToAction("Index");
            }
            db.Toplantilar.Remove(toplanti);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        [Authorize]
        public ActionResult CreateLink(int? id,bool? ozel)
        {
            if (id == null || ozel == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var toplanti = db.Toplantilar.Find(id);
            
            if (toplanti == null || User.Identity.GetUserId() != db.Toplantilar.Find(id).YoneticiID )
            {
                return RedirectToAction("Index");
            }

            var link = new Link()
            {
                ToplantiID = toplanti.ID,
                OzelMi = ozel.Value
            };

            db.Linkler.Add(link);
            db.SaveChanges();

            return RedirectToAction("Yonet", new { id = toplanti.ID });
        }

        [Authorize]
        public ActionResult DavetSil(int? id)
        {
            if (id == null || db.Katilimcilar.Find(id) == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var davet = db.Katilimcilar.Find(id);
            
            var toplanti = db.Toplantilar.Find(davet.ToplantiID);

            if (toplanti == null || User.Identity.GetUserId() != toplanti.YoneticiID )
            {
                return RedirectToAction("Index");
            }


            db.Katilimcilar.Remove(davet);
            db.SaveChanges();
            return RedirectToAction("Yonet",  new { id= toplanti.ID } );

        }

        [Authorize]
        public ActionResult LinkSil(int? id)
        {
            if (id == null || db.Linkler.Find(id) == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var link = db.Linkler.Find(id);

            var toplanti = db.Toplantilar.Find(link.ToplantiID);

            if (toplanti == null || User.Identity.GetUserId() != toplanti.YoneticiID)
            {
                return RedirectToAction("Index");
            }


            db.Linkler.Remove(link);
            db.SaveChanges();
            return RedirectToAction("Yonet", new { id = toplanti.ID });

        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateDavet()
        {
            var form = Request.Form;

            var TopId = form["toplantiId"];
            var mail = form["mail"];
            var konusmaci = form["konusmaciMi"];
            int toplantiId;
            bool konusmaciMi;

            try
            {
                toplantiId = Convert.ToInt32(TopId);
                konusmaciMi = konusmaci == null ? false : true  ;
            }
            catch (Exception e)
            {
                return RedirectToAction("Index");
            }


            if (db.Toplantilar.Find(toplantiId)==null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var toplanti = db.Toplantilar.Find(toplantiId);
            if (User.Identity.GetUserId() != toplanti.YoneticiID)
            {
                return RedirectToAction("Index");
            }

            var davetli = userManager.FindByEmail(mail);
            if (davetli == null)

Vmeet/Vmeet/Views/Toplanti/Chat.cshtml
@{
    ViewBag.Title = "Chat";
}
<fieldset>
    <legend style="color:orangered">Welcome To  Satya's signalR MVC Group Chat Club</legend>
</fieldset>
<div class="form-group col-xl-12">
    <label style="color: blue; font-style: oblique;font-size: medium" id="label1">Write Your Message Here!</label><br />
    <textarea class="form-control" rows="4" cols="40" id="message" placeholder="Share what's in your mind..."></textarea>
    <br />
    <input type="button" class="btn btn-primary" id="sendmessage" value="Send" />
    <br />
    <br />
    <label style="color: blue;font-style:oblique;font-size:medium" id="label2">Group Chat Conversations History</label>
    <div class="container chatArea">
        <input type="hidden" id="displayname" />
        <ul id="discussion"></ul>
    </div>
</div>
@section scripts {
    <script src="~/Scripts/jquery.signalR-2.2.3.min.js"></script>
    <script src="~/signalr/hubs"></script>
    <script>

        $(function () {
            var chat = $.connection.chatHub;
            chat.client.addNewMessageToPage = function (name, message) {
                $('#discussion').append('<ul style="list-style-type:square"><li><strong style="color:red;font-style:normal;font-size:medium;text-transform:uppercase">' + htmlEncode(name) + '  ' + '<strong style="color:black;font-style:normal;font-size:medium;text-transform:lowercase">said</strong>'
                    + '</strong>: ' + '<strong style="color:blue;font-style:oblique;font-size:medium">' + htmlEncode(message) + '</strong>' + '</li></ul>');
            };
            $('#displayname').val(prompt('Your Good Name Please:', ''));
            $('#message').focus();
            $.connection.hub.start().done(function () {
                $('#sendmessage').click(function () {
                    chat.server.send($('#displayname').val(), $('#message').val());
                    $('#message').val('').focus();
                });
            });
        });
        function htmlEncode(value) {
            var encodedValue = $('<div />').text(value).html();
            return encodedValue;
        }
    </script>  
}

Vmeet/Vmeet/Views/Toplanti/Index.cshtml
@model Vmeet.Models.ToplantiyaKatilViewModel
@{
    ViewBag.Title = "Index";
}

<div id="page-wrapper">
    <form id="login-form" method="post" action="@Url.Action("Join", "Toplanti")">
        @Html.AntiForgeryToken()
                <div class="content">
                    <div class="popup-label">
                        Profil resmi seç
                    </div>
                    <hr />
                    <div id="choose-avatar" class="row">
                        <div id="inner">
                            <input type="hidden" name="toplantiId" id="toplantiId" value="@Model.ToplantiID" />
                            <input type="hidden" name="anahtar" id="toplantiId" value="@Model.anahtar" />
                            <input type="radio" name="avatar" id="radio-0" value="-1" hidden checked="checked">
                            @foreach (var item in Model.Avatarlar)
                            {
                                <input type="radio" name="avatar" id="radio-@item.ID" value="@item.ID" /><label id="label-radio-@item.ID" style="display:inline;box-shadow:none;" for="radio-@item.ID"><img style="width:19%" class="rounded-circle avatar-icon" src="@Url.Action("Avatar","Toplanti", new { avatarId = item.ID })" alt="@item.Dosya.DosyaIsmi" /></label>
                            }
                        </div>
                    </div>
                    <br>
                    <div class="form-group">
                        <label>İsim</label>
                        <input name="isim" type="text" class="form-control" id="isim" placeholder="İsminizi giriniz">
                    </div>
                    <button type="submit" class="btn btn-primary login" style="width:70%;margin:0% 15%; ">Başla</button>
                </div>
    </form>
</div>

@section scripts{
    <script>
        function value(valu) {
            $("#toplantiId").val(valu);
        }
        $(document).ready(function () {
            $('#choose-avatar input:radio').addClass('input_hidden');
            $('#choose-avatar label').click(function () {
                $('#choose-avatar img').removeClass('selected');
                $(this).addClass('selected').siblings().removeClass('selected');
                $(this).children(0).addClass('selected');
            });
        });
    </script>
}

Vmeet/Vmeet/Views/Toplanti/baslamamis.cshtml
@model Vmeet.Models.BaslamamisToplantiViewModel

@{
    ViewBag.Title = "baslamamis";
}
<div  class="container" style="background-image:url('@Url.Content("~/Content/images/baslamamis.jpg")');background-repeat: no-repeat;background-size: cover;">
<div class="row" style="width: 1130px; margin-left: 108px; margin-top:110px">
        <div class="col-md-8" style="left: 115px;">
            <div class="thumbnail" style="border: 2px solid #50DF42;width: 650px;">
<center><p><font face="tahoma" size="2" color="#918a8a">
<br /> 
<b>- Bu toplantı henüz başlamamıştır -</b></font></p></center>

<div>
	<center><p><font face="tahoma" size="5" color="#38aa1e">
<b>@Html.DisplayFor(model => model.ToplantiAdi)</b></font></p></center>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Toplantı Yöneticisi :
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Yonetici)
        </dd>

        <dt>
            Toplantı Konusu :
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ToplantiKonusu)
        </dd>

        <dt>
            Başlama Tarihi :
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ToplantiBaslamaZamani)
        </dd>

        <dt>
            Toplantı Süresi :
        </dt>

        <dd>
            @Model.ToplantiSuresi.Hours saat, @Model.ToplantiSuresi.Minutes dakika
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Listeye geri dön","Index","Toplantilar")
</p>
</div>
        </div>
    </div>
	</div>

Vmeet/Vmeet/Views/Toplanti/bitmis.cshtml
@model Vmeet.Models.BitmisToplantiViewModel

@{
    ViewBag.Title = "baslamamis";
}

<h2>Bu Toplanti @Model.ToplantiBitisZamani.ToString("F", new System.Globalization.CultureInfo("tr-TR")) tarihinde bitmistir</h2>

<div>
    <h3>@Html.DisplayFor(model => model.ToplantiAdi)</h3>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Toplanti yoneticisi :
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Yonetici)
        </dd>

        <dt>
            Toplanti konusu :
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ToplantiKonusu)
        </dd>

        <dt>
            Toplanti ciktisi :
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ToplantiCiktisi)
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Listeye geri dön","Index","Toplantilar")
</p>